### ISSUE TITLE
Yo stilic, just a question

### ISSUE THREAD

**Issue by MemeHoovy** [Stilic/FNF-FlatyEngine#5]
I know this isn't an issue & I shouldn't use the issue tracker for this, but, is it ok if I friend request you on discord? because your epic
(again, sorry for wasting your time, I just wanted to know)

![EBoUdBbUIAEcCuG (3)](https://user-images.githubusercontent.com/97995998/200922130-b06071b4-56c3-47fa-bf0f-d95616a4b56c.jpg)

**Comment by Stilic** [comment]
yes
