### ISSUE TITLE
Constant (slight) memory leak

### ISSUE THREAD

**Issue by MemeHoovy** [Stilic/FNF-FlatyEngine#7]
This seems to be an issue that occurs in any song you play, the memory would slowly rise, and then fall back down due to GC.
Idk what the cause of the memory leak is, but it might become an actual issue later down the line, but don't count on that.

**Comment by Stilic** [comment]
this "leak" is caused by the music streaming stuff

**Comment by MemeHoovy** [comment]
good to know
